/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        gradient:        'var(--primary)',
        blue:            'var(--blue)',
        brandBlue:       'var(--brandBlue)',
        blueSecondary:   'var(--blueSecondary)',
        purple:          'var(--purple)',
        brandPurple:     'var(--brandPurple)',
        red:             'var(--red)',
        redSecondary:    'var(--redSecondary)',
        green:           'var(--green)',
        greenSecondary:  'var(--greenSecondary)',
        gold:            'var(--gold)',
        goldSecondary:   'var(--goldSecondary)',
        light:           'var(--light)',
        gray:            'var(--gray)',
        graySecondary:   'var(--graySecondary)',
        grayThird:       'var(--grayThird)',
        grayFourth:      'var(--grayFourth)',
        dark:            'var(--dark)',
        darkSecondary:   'var(--darkSecondary)',
        darkThird:       'var(--darkThird)',
      
        h1:              'var(--h1)',
        h2:              'var(--h2)',
        h3:              'var(--h3)',
        h4:              'var(--h4)',
        h5:              'var(--h5)',
        h6:              'var(--h6)',
        caption:         'var(--caption)',
        button:          'var(--button)',
        buttonSmall:     'var(--buttonSmall)',
        paragraph:       'var(--paragraph)',
        link:            'var(--link)',
      },
      fontSize: {
         h1:              'var(--h1)',
         h2:              'var(--h2)',
         h3:              'var(--h3)',
         h4:              'var(--h4)',
         h5:              'var(--h5)',
         h6:              'var(--h6)',

         caption:         'var(--caption)',
         button:          'var(--button)',
         buttonSmall:     'var(--buttonSmall)',
         paragraph:       'var(--paragraph)',
         link:            'var(--link)',
      },
    },
  },
  plugins: [],
}

